item_per_page: 15
format:
  request_date_time_format: "%Y-%m-%d %H-%M"
  date_time_format: "%Y_%m_%d_%H-%M-%S"
  picture_size: "60x60"
specifications:
  minimum_item: 1
  maximum_item: 4
user:
  item_per_page: 9
